### ISSUE TITLE
เขียนผิด หน้าอัปโหลดบทความวิชาการ

### ISSUE THREAD

**Issue by ongsalt** [PCSHSBR/symposium2023#1]
ใน[หน้าอัปโหลดบทความวิชาการ](https://3rdpss2023.pcshsbr.ac.th/my-project/edit/step-4-article) ข้อความมันไม่ตรงกันอยู่
![image](https://github.com/PCSHSBR/symposium2023/assets/58396464/fe4642c5-cd6a-4fc1-a639-f4bfe6f41936)

**Comment by ptsgrn** [comment]
ขอบคุณมากครับที่แจ้งเข้ามา ยังไงถ้าเจอตรงไหนอีกรบกวนด้วยนะครับ

**Comment by ptsgrn** [comment]
@all-contributors please add @ongsalt for content
