### ISSUE TITLE
Notably scroll lag when navigate to home page multiple time.

### ISSUE THREAD

**Issue by ongsalt** [PCSHSBR/symposium2023#5]
Especially on low-end mobile device even when navigating for just 2 times. On (my) desktop it take around 5 time to make it noticable. I suspect that 3d model in Banner component is the root of this issue.

**Steps to reproduce the issue**
1. open home page
2. navigate to other page using navbar menu (without refreshing the page)
3. navigate back to home page (also without refreshing the page)
4. repeat step 2 and step 3

**Comment by ptsgrn** [comment]
Your guess is correct. @PhubestSrikooon?
